Section "InputClass"
    Identifier "Minarch touchpads"
    MatchIsTouchpad "on"
    MatchDriver "libinput"
    Option "NaturalScrolling" "true"
    Option "Tapping" "true"
    Option "DisableWhileTyping" "true"
EndSection

Section "InputClass"
    Identifier "Minarch mice (not pointing sticks)"
    MatchIsPointer "on"
    MatchIsTouchpad "off"
    MatchDriver "libinput"
    MatchTag "minarch-mouse"
    Option "NaturalScrolling" "true"
EndSection

Section "InputClass"
    Identifier "Minarch US keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us"
EndSection
